#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias dir='ls -F'
alias desk='cd ~/Desktop'
alias update_prezto='cd "${ZDOTDIR:-$HOME}/.zprezto" && git pull && git submodule update --init --recursive'
alias vi='vim --noplugin'
alias view='vim -R --noplugin'
alias add='awk "{s+=\$1} END {printf \"%.2f\n\", s}"'
